// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9N5MRcuJeZHD9hcEnnN61siyU7GUFvV4',
    appId: '1:825102963635:web:8809e8d32f749afd7b31c6',
    messagingSenderId: '825102963635',
    projectId: 'lost-and-found-3b1f5',
    authDomain: 'lost-and-found-3b1f5.firebaseapp.com',
    storageBucket: 'lost-and-found-3b1f5.firebasestorage.app',
    measurementId: 'G-5YVH7M01L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0Yhn8WOlxlRs7v1gbeBaFmF0ObX99ys',
    appId: '1:825102963635:android:b8ed7f66ea19838d7b31c6',
    messagingSenderId: '825102963635',
    projectId: 'lost-and-found-3b1f5',
    storageBucket: 'lost-and-found-3b1f5.firebasestorage.app',
  );

}